### ISSUE TITLE
Qt5 immodule: build failure as "target.path is not defined"

### ISSUE THREAD

**Issue by rathsky** [uim/uim#103]
On Arch, building the qt5 immodule from git now fails with:

>make[3]: Entering directory '/tmp/makepkg/uim-git/src/uim/qt5/edittest'
>/usr/bin/qmake-qt5 -o Makefile.qmake ../../qt4/edittest/edittest.pro
>WARNING: target.path is not defined: install target not created
>
>make[3]: Nothing to be done for 'all'
>make[3]: Leaving directory '/tmp/makepkg/uim-git/src/uim/qt5/edittest'
>make[2]: Leaving directory '/tmp/makepkg/uim-git/src/uim/qt5/edittest'
>Making all in immodule
>make[2]: Entering directory '/tmp/makepkg/uim-git/src/uim/qt5/immodule'
>make  -f Makefile.qmake INSTALL_ROOT= all 
>make[3]: Entering directory '/tmp/makepkg/uim-git/src/uim/qt5/immodule'
>make[3]: Makefile.qmake: No such file or directory
>make[3]: *** No rule to make target 'Makefile.qmake'. Stop.

Configure was created with:

>./make-wc.sh --prefix=/usr --libexecdir=/usr/lib/uim --with-anthy-utf8 --with-qt4-immodule --with-qt5 --with-qt5-immodule

**Comment by rathsky** [comment]
Logs from make-wc.sh and make.

[logs.zip](https://github.com/uim/uim/files/766856/logs.zip)

**Comment by rathsky** [comment]
Apparently that's caused by an invalid
>load(qt_plugin) 
in
> qt5/immodule/quimplatforminputcontextplugin.pro.in

Trouble is, even if it's patched, it'll now still fail with 
>g++ -Wl,-O3,--sort-common,--as-needed,-z,relro -Wl,-O1 -Wl,-O1,--sort-common,--as-needed,-z,relro -o uimplatforminputcontextplugin quimplatforminputcontext.o candidatewindowproxy.o caretstateindicator.o plugin.o qhelpermanager.o qtextutil.o quiminfomanager.o util.o quiminputcontext_compose.o moc_quimplatforminputcontext.o moc_candidatewindowproxy.o moc_caretstateindicator.o moc_plugin.o moc_qhelpermanager.o moc_qtextutil.o   -L/tmp/makepkg/uim-git/src/uim/uim -L/tmp/makepkg/uim-git/src/uim/replace -L/tmp/makepkg/uim-git/src/uim/replace/.libs -L/tmp/makepkg/uim-git/src/uim/uim/.libs -lreplace -luim -luim-scm -luim-x-util -lX11 -luim-counted-init -lQt5Widgets -lQt5X11Extras -lQt5Gui -lQt5Core -lGL -lpthread
>/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/../../../../lib/Scrt1.o: In function \`_start':
>(.text+0x20): undefined reference to `main'

**Comment by rathsky** [comment]
To be fixed with the changes in https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=uim-debian

**Comment by dai-vdr** [comment]
https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=uim-debian&id=204269740f21d4b11e763f625c8f7f873d065c01

**Comment by dai-vdr** [comment]
fixed by #108
