### ISSUE TITLE
Emacs: uim-mode breaks Shift+Arrow selection

### ISSUE THREAD

**Issue by CyberShadow** [uim/uim#116]
Hi,

I installed uim 1.8.6 using my package manager, and configured Anthy as the default input method.

I run Emacs 25.3.1 using `emacs -q`, and evaluate:

```el
(require 'uim)
(uim-mode)
```

In `uim-mode`, Shift+Arrow selection stops working. I need to deactivate `uim-mode` to be able to use Shift+Arrow selection again.

The same problem appears when using uim with LEIM. However, when using LEIM with Emacs' built-in `japanese` LEIM input method, the problem does not manifest, so it appears to be specific to uim.

I looked through the Anthy key binding pages in `uim-pref-gtk3`, and removed the `<Shift>left` and `<Shift>right` bindings from extend/shrink segment, however the problem persists, and I didn't see anything regarding `<Shift>up` or `down`.

**Comment by kou** [comment]
Thanks for your report.
Can you try 6a0bae5?

**Comment by CyberShadow** [comment]
It works, thanks!
