### ISSUE TITLE
Add autoload cookies for uim-el

### ISSUE THREAD

**Issue by arunisaac** [uim/uim#118]
Hi, I'm improving the Guix package for uim.

It would be nice if we had autoload cookies for `uim-mode`, `uim-mode-switch` and any other entry-point commands so that `update-directory-autoloads` could pick it up and automatically create an autoloads file.

Thanks.

**Comment by kou** [comment]
Can you create a patch for it?

**Comment by arunisaac** [comment]
Ok, I'll do it.
