### ISSUE TITLE
uim 1.8.7 build failure with `--with-libgcroots=installed`

### ISSUE THREAD

**Issue by dai-vdr** [uim/uim#130]
when passing `--with-libgcroots=installed` to `configure` of uim 1.8.7, build failure:

```
make[3]: *** No rule to make target '../sigscheme/libgcroots/libgcroots.la',
needed by 'libuim-scm.la'. Stop. 
```

reverting 08e1aec6c9f6445e235aa884228412d9973c7b28, build successfully.
when passing `--with-libgcroots=no` to `configure`, build successfully too.

**Comment by kou** [comment]
I've fixed and released a new version.
