### ISSUE TITLE
cannot launch uim-tomoe-gtk

### ISSUE THREAD

**Issue by iyagicom** [uim/uim#142]
I want to write by hand but can not launch uim-tomoe-gtk.
What should I do?
![2019-03-03 01-52-48](https://user-images.githubusercontent.com/15052400/53684939-46c0cb80-3d57-11e9-9dfb-208ee4c9374c.png)

**Comment by kou** [comment]
Could you show the output of `which uim-tomoe-gtk` on terminal?

**Comment by iyagicom** [comment]
> Could you show the output of `which uim-tomoe-gtk` on terminal?

There is no response or message.
Only line breaks.

**Comment by kou** [comment]
Could you paste screenshot of the terminal when you did?

**Comment by iyagicom** [comment]
[vokoscreen-2019-03-09_03-52-29.zip](https://github.com/uim/uim/files/2947085/vokoscreen-2019-03-09_03-52-29.zip)
動画です。

**Comment by kou** [comment]
Thanks.
uim-tomoe-gtk isn't installed. It seems that Ubuntu doesn't provide uim-tomoe-gtk package.
And Tomoe isn't maintained. So you can't use uim-tomoe-gtk. Sorry.
