### ISSUE TITLE
Crashes on startup in Wayland/Qt

### ISSUE THREAD

**Issue by shocklateboy92** [uim/uim#155]
With `QT_IM_MODULE=uim`, all apps crash on startup on Wayland:
![Screenshot_20200223_162552](https://user-images.githubusercontent.com/856493/75123103-51a3f880-5659-11ea-94a5-196fbb407d29.png)

I really don't know much about how uim code works, it seems to happen on [line 154 of plugin.cpp](https://github.com/uim/uim/blob/865bead3e4fae8c15e9321ff388e0a662c035897/qt4/immodule/plugin.cpp#L154)
![Screenshot_20200223_162827](https://user-images.githubusercontent.com/856493/75123134-9596fd80-5659-11ea-9a80-bdad5ddaa711.png)
when it tries to invoke the `xkb` plugin. I can't really follow the code from there.

**Comment by keithbowes** [comment]
Yeah, I noticed the same thing since I installed the qtwayland plugin.  I suppose the code will have to be changed not to use X11 calls under Wayland, like was done for GTK+ in 1.8.7.  If you have Xwayland, you can use the -platform argument, e.g. `kbounce -platform xcb`.

**Comment by kou** [comment]
Do you know a Qt API to detect whether the current process uses X11 or not?

**Comment by eniehack** [comment]
How about `platformName()`?
https://doc.qt.io/qt-5/qguiapplication.html#platformName-prop

**Comment by shocklateboy92** [comment]
Okay, I finally have free time to work on open source projects again. 
@kou : will you have some time to work with me to fix this in the coming weeks?

**Comment by kou** [comment]
Yes.
I already added CI jobs for Qt4 and Qt5.

**Comment by shocklateboy92** [comment]
Awesome! Please send a mail to the email address listed on my github
profile with your preferred way of being contacted, and let's try to find
time for a pair programming session. :-)

**Comment by kou** [comment]
Ah, sorry.
I can review but I don't have enough time to do pair programming...

Are there people to do it here?

**Comment by RaphyJake** [comment]
Any update on this issue?
