### ISSUE TITLE
xim: Handle missing fonts more gracefully

### ISSUE THREAD

**Issue by dalcde** [uim/uim#156]
Currently, `uim-xim` crashes at https://github.com/uim/uim/blob/d17a158640545f8ddf3bb0f8cffe90bdc64651c2/xim/ximic.cpp#L91 when the system is missing the fonts hardcoded at https://github.com/uim/uim/blob/d17a158640545f8ddf3bb0f8cffe90bdc64651c2/xim/convdisp.cpp#L73
This causes `xim-uim` to crash and generally renders all applications using `xim` to become unresponsive (and usually crash). The cause of this crash would be mysterious to the user, especially since the font set is hardcoded in the code so they are not actively using a non-existent font, and no obvious error message is presented to the user.

**Comment by kou** [comment]
Sorry for late response.
Could you show a backtrace on crash?
Is `XwcDrawImageString()` with `mFontset == NULL` wrong?

**Comment by RangHo** [comment]
I'm pretty sure PR #177 addresses this, as the hardcoded font names were causing the crash. Maybe it is fine to mark this as closed?

**Comment by kou** [comment]
OK. Thanks for confirming it.
