### ISSUE TITLE
A possible wrong pointer usage in uim-ipc.c

### ISSUE THREAD

**Issue by tsutsui** [uim/uim#169]
On building uim-1.8.8 on NetBSD/amd64 9.1, gcc 7.5.0 complains during uim-ipc.c build:
```
uim-ipc.c:205:36: warning: comparison between pointer and zero character constant [-Wpointer-compare]
       if (cmd_name && cmd_name + 1 != '\0')
```

https://github.com/uim/uim/blob/a1cf71ec3719389874c42dd4c719a15509983485/uim/uim-ipc.c#L203-L208
It looks this comparison should use `cmd_name[1]` or `*(cmd_name + 1)` to check the next charactor of the separator, not `cmd_name + 1` pointer.

**Comment by kou** [comment]
Good catch!
