### ISSUE TITLE
Numeric conversions with ASCII numbers do not work within Firefox windows

### ISSUE THREAD

**Issue by toshjp** [uim/uim#175]
I am currently on MX Linux 21 based on Debian 11 and within Firefox windows numeric conversons do not work when candidates include ASCII numbers, i.e. single width numbers, which I suppose correspond to dictionary entries with `#0`.
When I start Firefox with `GTK_IM_MODULE=xim`, numeric conversions work fine (though with not uim but xim) but with `GTK_IM_MODULE=uim` candidates with single width numbers do not even show and become blank.
Then when I select the blank places of these candidates, null strings are inserted.

I have the Debian official package of uim 1.8.8 installed and Firefox is the latest version 94.0.1 (64-bit).
Does anybody have the same problem? Any suggestions are welcome.

**Comment by kou** [comment]
Could you try it with gedit instead of Firefox?

**Comment by toshjp** [comment]
I've had no problem with other applications so far including gedit.

**Comment by kou** [comment]
OK.
It seems that this is a Firefox problem. Could you report this to Firefox?

**Comment by toshjp** [comment]
I don't mind doing that but I don't know what relevant information they will need to fix it.
I'm afraid rather few people know about uim and even less about how it works.
Or do you think they can figure it out?

**Comment by kou** [comment]
Firefox developers and uim developers can work altogether.
If Firefox developers don't know enough information for uim, they can ask it for uim developers.

As the first, we need to report an instruction to reproduce this case on Firefox developers environment.

**Comment by toshjp** [comment]
I have filed a tentative bug report on Bugzilla, if that could be of any help.
With any luck, it might bring something. So let's wait and see.

https://bugzilla.mozilla.org/show_bug.cgi?id=1741473

**Comment by tattsan** [comment]
I've commented on  [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1741473#c2). As I wrote, utf-8-modification makes the candidate visible, but with garbage string like this:
```
5人����#0人
```

`#0人` should appear only in uim internally, so I feel the issue is on the uim side.

The utf-8 modification mensioned above is on [tattsan/PKGBUILD-uim-skk-utf8](https://github.com/tattsan/PKGBUILD-uim-skk-utf8) (script for Arch Linux package). The numeric conversion code is modified in [uim-skk-1.8.8-utf8-3.patch](https://github.com/tattsan/PKGBUILD-uim-skk-utf8/blob/main/uim-skk-1.8.8-utf8-3.patch).

And as I wrote in [the second comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1741473#c3), when the number is two or more digits, the bug doesn't appear. Does this also true for EUC-JP environment? @toshjp

**Comment by toshjp** [comment]
Thanks for your comments, @tattsan.

> And as I wrote in the second comment, when the number is two or more digits, the bug doesn't occur. Is this also true in EUC-JP environment?

I didn't notice but that's correct.
This issue affects numbers with only one digit. Then also skk dictionaries have entries wth only single digits from `#0` to `#9`.
This could suggest it has to do with the particular form of these numeric entries and the handling of these entries in the program.
And when I come to look at it this way, your another post on Bugzilla seems all the more relevant, doesn't it?

**Comment by tattsan** [comment]
For the meaning of ``#0`` to ``#9``, see [here](http://quruli.ivory.ne.jp/document/ddskk_14.2/skk_4.html#g_t_00e6_0095_00b0_00e5_0080_00a4_00e5_00a4_0089_00e6_008f_009b) .

**Comment by tattsan** [comment]
In my utf8-patched environment, the following patch for  `skk_merge_replaced_numeric_str() `
in `skk.c` soleved the issue.

```
--- skk.c.orig  2022-09-27 01:02:26.855038427 +0900
+++ skk.c       2022-09-27 01:05:19.766028180 +0900
@@ -1582,6 +1582,7 @@
       numlst_ = CDR(numlst_);
     }
   }
+  str[newlen] = '\0';

   return MAKE_STR_DIRECTLY(str);
 }
```

@toshjp , please test this in EUC-JP environment.

**Comment by kou** [comment]
Ah, we need `\0` here. Could you open a pull request for the fix?
