### ISSUE TITLE
Build fails with ERROR: 'IT_PROG_INTLTOOL' must appear in configure.ac for intltool to work.

### ISSUE THREAD

**Issue by calimeroteknik** [uim/uim#179]
Building 492f4f70 with autoconf 2.71 and automake 1.16.5, running ./autogen.sh yields:
```
ERROR: 'IT_PROG_INTLTOOL' must appear in configure.ac for intltool to work.
autoreconf: error: intltoolize failed with exit status: 1
```
Full build log here: [uim-buildlog.txt](https://github.com/uim/uim/files/8286075/uim-buildlog.txt)

**Comment by kou** [comment]
Could you show the output of `bash -x $(command -v intltoolize) --copy --force --automake`?

**Comment by calimeroteknik** [comment]
Here you go: [intltoolsize-log.txt](https://github.com/uim/uim/files/8295520/intltoolsize-log.txt)

**Comment by kou** [comment]
Thanks.
I've fixed this.
