### ISSUE TITLE
Cannot disable display of toolbar

### ISSUE THREAD

**Issue by holmesrichards** [uim/uim#184]
Under Linux Mint 21.0 Cinnamon, the toolbar apparently is started up by default when logging in. It is not something I need. In uim-pref-gtk there is a Toolbar pane with a Display dropdown that can be set to Always, Based on mode, or Never. However setting it to "Never" appears to have no effect.

**Comment by kou** [comment]
Could you try running `sudo update-alternatives --config uim-toolbar` and choose `/bin/true` to disable toolbar entirely?

**Comment by natewind** [comment]
I just had a similar problem in Ubuntu 20.04: even with `(define toolbar-display-time 'never)`, the toolbar would appear on login and only disappear after about a minute or two. But this indeed helped:

```
sudo update-alternatives --install /usr/bin/uim-toolbar uim-toolbar /bin/true 100
```

**Comment by holmesrichards** [comment]
This solves the problem, thanks.
