### ISSUE TITLE
Help required for finding kana layout of uim

### ISSUE THREAD

**Issue by niruvt** [uim/uim#185]
This isn't really a bug-report in the software, but I wasn't able to find any reliable resource giving a key-layout of uim Kana keyboard. I am not a Japanese. Though I conceptually understand how a Kana keyboard is supposed to work, I have zero experience of using it. I am using `uim-anthy` package for inputting Japanese on MX GNU/Linux. Version details of the OS are as follows:

```
cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
```

Version details of uim are as follows:

```
uim 1:1.8.8-4+deb10u5
uim-anthy 1:1.8.8-4+deb10u5
```

I apologize if this issue is not suited here, but I didn't find any other suitable place for this. I have tried searching for images of Anthy layout, uim layout, but unfortunately in none of these attempts I succeeded. I would appreciate any kind of help regarding this.

**Comment by kou** [comment]
Could you run `uim-pref-gtk` and set the following configuration?

* "Anthy" in sidebar ->
* "Default kana input method" in "Toolbar" panel ->
* "Kana"

**Comment by niruvt** [comment]
@kou thanks a lot for your prompt response. I have already followed this method and enabled the Kana keyboard, but as I don't know which key means which Kana I am finding it difficult to actually use the Kana keyboard. Usually standard keyboards come with their layout images, e.g., the standard QWERTY keyboard uses [this](https://en.wikipedia.org/wiki/QWERTY#/media/File:KB_United_States.svg) layout or the Inscript layout used for the Devanagari script uses [this](https://en.wikipedia.org/wiki/InScript_keyboard#/media/File:Devanagari_INSCRIPT_Keyboard.JPG) layout. One can easily learn typing with these keyboards by looking at these images. Is there any such image for learning the Kana layout used by Anthy is my question.

**Comment by kou** [comment]
Ah, sorry.
https://ja.wikipedia.org/wiki/JIS%E3%82%AD%E3%83%BC%E3%83%9C%E3%83%BC%E3%83%89#/media/%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB:JIS_keyboard_character_layout_US_ANSI_comparison.svg

BTW, most Japanese uses "Romaji" not "Kana" to input Japanese. (I also use "Romaji" not "Kana".)
