### ISSUE TITLE
uim-fep returning error: locale not supported

### ISSUE THREAD

**Issue by BuddhiLW** [uim/uim#191]
I can't figure out how should I set up locale so it's supported by uim-fep. I seem unable to find out this information anywhere.

My system:
OS: Ubuntu 23.04 x86_64
Kernel: 6.2.0-23-generic

**Comment by kou** [comment]
Does `LOCALE=C uim-fep` work?

**Comment by kou** [comment]
https://help.ubuntu.com/community/Locale may help you.

**Comment by BuddhiLW** [comment]
I was trying many things. I installed 

```
guix install glibc-locales
```

And it worked. I installed  `uim` using guix, although I'm on Ubuntu.
