### ISSUE TITLE
GTK+2 programs stuck with Byeoru

### ISSUE THREAD

**Issue by HexagonWin** [uim/uim#195]
Hello. I'm using Slackware 15.0 amd64. This issue occurs with both the latest release and the git master.
On GTK+2 based programs such as Palemoon, OpenOffice, Xarchiver, SciTE, when I type korean characters using byeoru the first character typed properly gets registered but when i make the next input, the program suddenly stops and ceases to work. I have to forcefully kill the program.
From many observations i found out that on the GTK+2 file chooser dialog i can type more than one character though I get significant lags (though sometimes that also stops and gets stuck).

Anyone has the same symptoms? I'm using another IM (nabi) for GTK+2 programs ATM but that also has issues with space input working weird. (안녕 여러분 ! -> 안녕여 러 분!)

**Comment by kou** [comment]
Sorry, please upgrade to GTK 3 or 4.

GTK 2 has reached EOL:

https://blog.gtk.org/2020/12/16/gtk-4-0/

> GTK 2 has reached the end of its life

**Comment by HexagonWin** [comment]
@kou I realized the same issue also occurs on GTK+3 programs, though it happens a bit less.
It *always* happens when I open Firefox and the first character I type is a korean character written with byeoru.
When I have uim-xim open in a terminal, when the issue occurs and the program stops I get these stdouts. (Identical with both GTK+2 and GTK+3 programs):
```
XIM_ERROR received.
 imid = 11
 error_code = 13
 message = ()
```
Now that this also applies to GTK+3, I guess this issue should be reopened/renamed but I don't know how to do so.
