### ISSUE TITLE
gtk im module shows black boxes as mode indicator

### ISSUE THREAD

**Issue by k7k7** [uim/uim#203]
uim: 1.8.8
OS: Debian sid

If bridge-show-input-state? is set to #t, gtk im module shows a mode indicator. But its foreground- and background-color are same. So I cannot see the current mode.
![screenshot](https://github.com/uim/uim/assets/24509102/99d80b7e-ee89-4467-b64d-66916528d63e)
I don't use any desktop envirionment. My gtk settings are as follows:

~/.config/gtk-3.0/gtk.css
scrollbar
{
    -GtkScrollbar-has-backward-stepper: true;
    -GtkScrollbar-has-forward-stepper: true;
}

undershoot
{
    background-image: none;
}

~/.config/gtk-3.0/settings.ini
[Settings]
gtk-key-theme-name = Emacs
gtk-primary-button-warps-slider = false
gtk-overlay-scrolling = false

**Comment by kou** [comment]
Oh, could you find where we specify foreground/background colors for it?

**Comment by k7k7** [comment]
It seems color is not set to an indicator.
