### ISSUE TITLE
Current chicken does not implement syntax-case

### ISSUE THREAD

**Issue by rrthomas** [uim/uim#26]
When building uim-el, the following command is run:

csi -R syntax-case -q json-parser-expander.scm > json-parser-expanded.scm

However, chicken version 4 (the current version) does not support syntax-case, which is no longer installable from the current egg repository (for version 4).

This makes uim-el rather tricky to build from a checkout (as done, for example, by el-get).

The original commit message for the code that calls Chicken suggests that a similar method is possible with gauche, so perhaps that could be used instead if there's not an easy workaround for Chicken (I don't know, I'm not a seasoned Schemer).

**Comment by tomogui** [comment]
Build from AUR on 5.13.19-2-MANJARO failed. 
[pamac_build_log.txt](https://github.com/uim/uim/files/7561615/pamac_build_log.txt)

**Comment by kou** [comment]
We dropped support for regenerating `scm/json-parser-expanded.scm`. But we can still use the JSON parsing feature because we bundles the expanded file in our repository and source archive.
