### ISSUE TITLE
uim-byeoru (and may other im modules) follows system keyboard layout

### ISSUE THREAD

**Issue by YongJoonJoe** [uim/uim#33]
Summary: Compare to Japanese (and may Chinese), all of Hangul keyboard layouts without 'Hangul-romaja', 
their keyboard layout is depends on the actual (real?) position of the key, not depends on which alphabet is inputted.
As a result, when the system's keyboard layout is not QWERTY, uim-byeoru (and may other im modules) not
work properly, until Japanese works well.

Explanation:

I usually type 
1. Japanese(by dvorak) and English(by dvorak)
2. Hangul and English(by dvorak)
3. Sometimes, QWERTY

I'm using dvorak for system default keyboard layout.
When I wants to use QWERTY, I change layout by hot-key for system keyboard
layout.
So, it's not matter.
Also, I type Japanese by dvorak. So this also not matter. (It works well!)

However, when I type Hangul, uim-byeoru does not works well because
byeoru's keyboard layout is not compatible when the system keyboard layout is
not QWERTY.

This makes problems for me, and other 'not QWERTY system keyboard layout
users'.

The problem is that, (without 'Hangul romaja' layout),
All the Hangul keyboard layouts are not depend on which alphabet is inputted, 
but only depends on its actual position of key on a keyboard.

I think, this also matter who tried to type Hangul by Japanese keyboard. 
As you know, Japanese keyboard also have some different characters against ASCII keyboard and the others.
However, All the Hangul keyboard layouts are 'only' depends on actual position
of key. So, who wants to type Hangul by this im module may face to this problem.

I'm not sure this problem is depends on which component of uim, but I think it could be trouble .

For me, I could edit byeoru.scm for dvorak layout. But, this kind of method could not be general method. This method require very very long option list by combination of system keyboard layout and Hangul keyboard layout.

At least, config may require system keyboard layout.

**Comment by jhyeon** [comment]
@YongJoonJoe Could you please check whether uim master resolves this issue or not?  You might turn on the Byeoru option, "Refresh keyboard map at each switch into Hangul mode", if you often change the system layout between QWERTY and dvorak.

**Comment by jhyeon** [comment]
To me, this issue seems to have been resolved.  I suppose it may be closed.
@YongJoonJoe if you still have the problem, please feel free to reopen this issue.
