### ISSUE TITLE
emacs bridge(uim-el): Keymapping conflict / ignored key strokes

### ISSUE THREAD

**Issue by Araeos** [uim/uim#51]
See issue capitaomorte/yasnippet#539 for reproduction and further discussion.

## Description

The way uim grabs input within _emacs_ (with `uim-mode` enabled) seems to break some other minor/major modes. For example in _Auctex_ (enabled via `latex-mode`) the shortcut `C-c C-c` does not work when uim-mode is enabled (at least on my platform).
Please see the above mentioned issue for details.

EDIT: `latex-mode` and `uim-mode` are not enough to cause some keybindings to disappear. For example yasnippet or maybe flyspell mode may be required. But `uim-mode` is the only _required_ mode for this bug to appear, hence this report.

## Platform

I use uim(1.8.6) on arch linux (regularly updated) for some months now together with the newest versions of gnu emacs(24.4 and 25.0). So i don't think this is a new issue.

Maybe someone can reproduce this behaviour.

**Comment by kou** [comment]
I get the same problem.

Here is a workaround I found:

```elisp
(define-key uim-mode-map (kbd "C-c") nil)
```

We should have more suitable solution...

**Comment by Araeos** [comment]
This hotfix works for me too, nice.
Though I did not check for possible side effects.

**Comment by kou** [comment]
I'll commit the code one week later if nobody reports any problem.

**Comment by kou** [comment]
I've pushed the fix.
Thanks for your report!
