### ISSUE TITLE
qt4 immodule causes defunct processes of okular 

### ISSUE THREAD

**Issue by jhyeon** [uim/uim#54]
When qt immodules from commit 639046f507f4e3ebfb728415bea853ec50c63595 are in use, okular document viewer (4.14.3 and 4.13.3) produces defunct processes which multiply as one browses through the document.  This problem is not found in uim release 1.8.6.

Steps to reproduce:

1. open a pdf file with okular enabling qt4 immodule:

    $ env QT4_IM_MODULE=uim okular /usr/share/doc/latex-beamer-3.33/doc/beameruserguide.pdf &
    $ ps x | grep okular
     5305 pts/3    Sl     0:00 okular /usr/share/doc/latex-beamer-3.33/doc/beameruserguide.pdf
     5312 pts/3    Z      0:00 [okular] <defunct>
     5314 pts/3    Z      0:00 [okular] <defunct>
     5331 pts/3    Z      0:00 [okular] <defunct>
     5333 pts/3    Z      0:00 [okular] <defunct>

2. open the pdf file with okular disabling qt immodules:

    $ env -u QT_IM_MODULE -u QT4_IM_MODULE okular /usr/share/doc/latex-beamer-3.33/doc/beameruserguide.pdf &
    $ ps x | grep okular
     5473 pts/3    S      0:00 okular /usr/share/doc/latex-beamer-3.33/doc/beameruserguide.pdf

**Comment by jhyeon** [comment]
Closed this issue since I could not reproduce it on Ubuntu 14.04 LTS.

**Comment by jhyeon** [comment]
The problem occurs on Ubuntu 14.04 LTS if I pass `--without-qt4 --with-qt4-immodule` to the configure script.  I am not sure whether one should regard this as a uim bug or not.  It would be nevertheless nice if configure prevented this buggy combination of options.

**Comment by icy** [comment]
Within `--without-qt4` option, the candidate window should be disabled. However, it is still active for some reason. It may not be correct, but I define a macro to exclude all candidate codes, as in https://github.com/TheSLinux-forks/uim/commit/c18f5eb3821abb1342bc117975b5978f8751f40a and https://github.com/TheSLinux-forks/uim/commit/c4ac13795083200a05fc39c340642f1fc7731bb2 .
