### ISSUE TITLE
close() is called with a file descriptor value of (-1)

### ISSUE THREAD

**Issue by zephyrus00jp** [uim/uim#55]
In uim/skk.c, there is a place where close() can be called with a file descriptor value of (-1).
While this is not a strictly a bug, and close() simply returns with an error value,
it nevertheless creates a lot of noise when libuim is used inside a program that runs under
valgrind for memory check.
(For example, I was testing mozilla's thunderbird mail client when I noticed this issue.)

So I suggest that it is fixed thusly:

diff --git a/uim/skk.c b/uim/skk.c
index c6117b7..d8f21aa 100644
--- a/uim/skk.c
+++ b/uim/skk.c
@@ -293,8 +293,8 @@ open_dic(const char *fn, uim_bool use_skkserv, const char *skkserv_hostname,
 	  mmap_done = 1;
 	}
       }
+      close(fd);
     }
-    close(fd);
   }
 
   di->addr = mmap_done ? addr : NULL;

**Comment by zephyrus00jp** [comment]
Oh, well, writing the patch in the comment field seems to mungle this very badly.
But I hope the developer understood the issue, and where the offending close() is located, and
where it should be moved.  It should be moved two lines above.

TIA

**Comment by kou** [comment]
Thanks for your patch!
It's reasonable. I've merged it.

**Comment by zephyrus00jp** [comment]
You are very welcome, and thank you for your quick feedback.
Happy Hacking (in the good old sense of the word.)
