### ISSUE TITLE
please release new version with Qt5 support

### ISSUE THREAD

**Issue by dai-vdr** [uim/uim#61]
i have tried to merge 1.8.6 and git master's Qt5 support,
but they have a great difference and cannot merge without any trouble.
so please release new verison uim with Qt5 support.

forwarding from https://bugs.debian.org/792151

---

uim should support Qt 5.
Now many KDE/Qt 5 applications are entering sid.

**Comment by rathsky** [comment]
Anki is a few weeks away from releasing 2.1, which switches it to Qt5.

uim will continue to lose users if it doesn't do a release before this as well. I don't understand what has kept the project from doing one in 3.5 years.

**Comment by clarcharr** [comment]
bumping this

**Comment by luigino** [comment]
Any news?

**Comment by XVilka** [comment]
Hopefully will be released soon.

**Comment by kou** [comment]
Done.
