### ISSUE TITLE
Uim 1.8.6 doesn't have updated codes.

### ISSUE THREAD

**Issue by ghpenguin** [uim/uim#64]
Apparently all source codes are dated back to 2013.
 
It's confusing because Debian Sid repository provides Uim-1.8.6 which gives impression it's latest Uim release that fixes Hangul bugs.

Uim-master has latest source codes but sigscheme was empty, which caused build error later on. 
the codes in uim directory references sigscheme files. Installation of sigscheme-0.8.5.tar.gz in sigscheme fixed it. 

Makefile in pixmaps directory contains many svg and png files that do not exist in the directory.

make[1]: Entering directory '/home/penguin/Maintain/uim-master/sigscheme'
make[1]: *** No rule to make target 'all'.  Stop.
make[1]: Leaving directory '/home/penguin/Maintain/uim-master/sigscheme'
Makefile:642: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

make[1]: Entering directory '/home/penguin/Maintain/uim-master/uim'
Makefile:2157: ../sigscheme/libgcroots.mk: No such file or directory
Makefile:2158: ../sigscheme/sigscheme.mk: No such file or directory
make[1]: *** No rule to make target '../sigscheme/sigscheme.mk'.  Stop.
make[1]: Leaving directory '/home/penguin/Maintain/uim-master/uim'
Makefile:643: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

make[1]: Leaving directory '/home/penguin/Maintain/uim-master/po'
Making all in pixmaps
make[1]: Entering directory '/home/penguin/Maintain/uim-master/pixmaps'
make[1]: *** No rule to make target 'py.svg', needed by 'all-am'.  Stop.
make[1]: Leaving directory '/home/penguin/Maintain/uim-master/pixmaps'
Makefile:642: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

grep -n py.svg Makefile
183:    im_switcher.svg uim-dict.svg im_subst.svg py.svg pyunihan.svg \
540:IM_SUBST_SVGS = py.svg pyunihan.svg pinyin-big5.svg \

make[1]: Entering directory '/home/penguin/Maintain/uim-master/pixmaps'
make[1]: *** No rule to make target 'pyunihan.svg', needed by 'all-am'.  Stop.
make[1]: Leaving directory '/home/penguin/Maintain/uim-master/pixmaps'

188:    trycode.svg trycode_dark_background.svg null.png \
544:GENERATED_SVGS = $(IM_SUBST_SVGS) trycode.svg trycode_dark_background.svg
878:#trycode.svg: tcode.svg

**Comment by dai-vdr** [comment]
i am Debian uim package maintaner. Debian's uim 1.8.6 has many backported patches.
btw, you can get latest uim and sigscheme source with `git clone --recursive`, try this.

```bash
git clone --recursive https://github.com/uim/uim.git
cd uim/sigscheme/libgcroots && ./autogen.sh
cd .. && ./autogen.sh # uim/sigscheme
cd .. && ./autogen.sh # uim
./configure
```

**Comment by dai-vdr** [comment]
s/he could get latest code at #65
