### ISSUE TITLE
Some bugs  of uim 1.9.0

### ISSUE THREAD

**Issue by ghpenguin** [uim/uim#65]
Hi, 

Kudos to jhyeon.

My running environment of Uim 1.9.0 is:
Linux distribution: Debian 8.0 
English keyboard: Colemak 
Korean keyboard: Sebul Final 

uim set up for Hangul input

in .xinitrc file
export GTK_IM_MODULE=uim
export QT_IM_MODULE=uim
export XMODIFIERS="@im=uim"

uim-xim --engine=byeoru &

I ran uim-pref-gtk and assigned the Xorg keyboard map to Xkb menu for byeoru
$ uim-pref-gtk

Tested applications:
xfce4-terminal - works 
chrome 34.0 - works
OpenSCAD - works
Vim - works
iceweasel, Debian's alternative version of fire fox - doesn't respond
firefox 37.x - doesn't respond  
libreoffice - doesn't respond

**Comment by dai-vdr** [comment]
@jhyeon 
any comments?

**Comment by jhyeon** [comment]
Sorry for the long silence.  I was not aware of this report.
I just did a quick check with my private installation of uim (including the xkb support but older than 1.9.0).  It works with libreoffice writer 4.4.1.2 and firefox 31.5.0.  I am going to check soon with uim 1.9.0 and a newer version of firefox.

**Comment by jhyeon** [comment]
Sorry, from where can I download uim-1.9.0?

**Comment by dai-vdr** [comment]
@jhyeon thank you following up.
uim 1.9.0 not yet released, @ghpenguin uses uim master, i think.

**Comment by jhyeon** [comment]
uim master also works for me with libreoffice writer 4.4.1.2 and firefox 31.5.0.  It still remains to check with firefox 37.  A caveat is that I use the usual US layout.
@ghpenguin May I ask you what you mean by "doesn't respond"?  Do the alphanumeric characters appear not translated into Korean?  If so, could you please check whether the `strace` output of `firefox` contains a line like the following?
```
open("/usr/lib64/gtk-2.0/2.10.0/immodules/im-uim.so", O_RDONLY|O_CLOEXEC) = 21
```
You might do
```
$ strace -o firefox.strace firefox -no-remote
```
and stop `firefox` after a brief run.

**Comment by jhyeon** [comment]
I further tested uim commit caf65e97bb6ed4cd1268cbc608bba04fb2ba2354 against libreoffice writer 5.0.4.2 and firefox 38.6.1, and it worked for me.  I set the Byeoru layout to `Hangul 3-beol final generous` and the X keyboard layout to Colemak using the xkbmap file from http://forum.colemak.com/viewtopic.php?pid=8727#p8727 .  So, I suppose that this issue may be closed.
@ghpenguin if you still have the problem, please feel free to reopen this issue.
