### ISSUE TITLE
Cannot select candidate on GTK3 application

### ISSUE THREAD

**Issue by t-site** [uim/uim#77]
on GTK3 applications include Firefox 44 on Arch linux x86_64,
When I typed "さかたくんはさかたしにいった", I caught chnage only one word.
on GTK2 applications, no such bug. no IME engine error.
for example,
initilal candiate 阪田君は坂田氏にいった
change to 酒田クンは坂田氏にいった
then, press right allow key
阪田君は坂田氏にいった
rewind 酒田クン to 阪田君  .
I cannot change more than 2 words.
This Problem is not solved on git master.

**Comment by NaofumiHonda** [comment]
I also confirm this issue with the candidate windows of vertical type, however,
the problem does not occure with the one of horizontal or table types.
So I checked related source codes and found that the only essential differences
of those is  "emitting or not an index-change signal  in a selection change of candidates".
Although I don't understand why this signal emitting causes the problem, the following
patch resolves the issue for gtk3 case (and works well for gtk2 also).

-------------------------------------------------------------------------------------------------------------------------
*** ./gtk2/immodule/uim-cand-win-vertical-gtk.c.org   2015-06-09 16:30:40.000000000 +0900
--- ./gtk2/immodule/uim-cand-win-vertical-gtk.c 2016-05-24 21:23:28.000000000 +0900
***************
*** 272,278 ****
--- 272,280 ----

    if (cwin->index_changed) {
      cwin->index_changed = FALSE;
+ #if   0
      g_signal_emit_by_name(G_OBJECT(cwin), "index-changed");
+ #endif
    }

    return TRUE;
-----------------------------------------------------------------------------------------------------------------------

**Comment by dai-vdr** [comment]
@NaofumiHonda, Thank you for your investigation.
This signal emittion is introduced by bc40465e to avoid SEGV.
So I do not know the result of your comment-out.

**Comment by NaofumiHonda** [comment]
Thank you for related information. 
The suggested commitment just changes a timing of the signal emitting, and hence, 
my previous patch does nothing worse for this SEGV.

Now why the patch works?  I did further investigation.
A point is that:
Around the line 209 in gtk2/immodule/uim-cand-win-vertical-gtk.c,
the  code assumes that the conditions
path_currently_selected == false and cwin->candidate_index != idx
only hold for the case that  a candidate is selected by a mouse click.
Surely this assumption is true for gkt2 case. However, in gtk3 case, the same
conditions also hold when the candidate window becomes hidden by
changing a target word, which causes a wired phenomenon.
Therefore we need to consider the latter case also and
it has been done in the attached patch.

[patch.zip](https://github.com/uim/uim/files/307127/patch.zip)

**Comment by dai-vdr** [comment]
great works :+1: 
but how about moving up comment together?

```diff
--- a/gtk2/immodule/uim-cand-win-vertical-gtk.c
+++ b/gtk2/immodule/uim-cand-win-vertical-gtk.c
@@ -206,16 +206,19 @@ tree_selection_change(GtkTreeSelection *selection,
   g_return_val_if_fail(indicies, TRUE);
   idx = *indicies + cwin->display_limit * cwin->page_index;

+  if (path_currently_selected && cwin->candidate_index >= 0) {
+    /* if emit "index-changed" here and IM deactivates this candwin,
+     * activates new candwin and selects a candidate on new candwin
+     * from index-changed callback, SEGV occurs in gtk because gtk tries to
+     * select on old candwin after return of this tree_selection_change().
+     * To avoid SEGV, instead of emitting before selection change by gtk,
+     * emit after selection changed by gtk. */
+    cwin->index_changed = TRUE;
+  }
+
   if (!path_currently_selected && cwin->candidate_index != idx) {
     if (cwin->candidate_index >= 0) {
       cwin->candidate_index = idx;
-      /* if emit "index-changed" here and IM deactivates this candwin,
-       * activates new candwin and selects a candidate on new candwin
-       * from index-changed callback, SEGV occurs in gtk because gtk tries to
-       * select on old candwin after return of this tree_selection_change().
-       * To avoid SEGV, instead of emitting before selection change by gtk,
-       * emit after selection changed by gtk. */
-      cwin->index_changed = TRUE;
     }

     uim_cand_win_gtk_update_label(cwin);
```

**Comment by NaofumiHonda** [comment]
You are absolutely right. Thanks!
