### ISSUE TITLE
tables/wb86.table  is missing 

### ISSUE THREAD

**Issue by scateu** [uim/uim#78]
I managed to find a wb86.table in a 1.7.x version uim from BSD repo.

My simple fix is as following:
https://github.com/scateu/uim-fep-wb86

Perhaps it is necessary to add a `uim-wb86`  package for debian?

Thanks.

**Comment by dai-vdr** [comment]
`tables/wb86.table` and `tables/zm.table` are auto generated files into tarball.
They are just not included by, and not distributed by Debian package.
Please file this issue to Debian BTS.
