### ISSUE TITLE
anyone see the overlay character candidate list on any window tiling system? (e.g. i3, sway)

### ISSUE THREAD

**Issue by wind0204** [uim/uim#82]
Hi I'm from Korea and using uim(byeoru) on sway. It seems working well so far except that it won't display the candidate list for hanja(chinese characters that's called kanji in Japan) when I launched the feature. When I want to write a hanja I have to try hitting all the number until I have found the hanja since I don't see them, nor their meaning and sound.

As the title says, I just want to know if there is anyone who sees the pop-up overlay candidate list, especially on sway. If there is no one I would like to request both of the development teams the feature.

I guess I wouldn't be helpful writing C code since it has to do with some negotiation between the development teams (sway and uim and probably more)

from Korea
Best Wishes

**Comment by wind0204** [comment]
P.S. I'm not really much of a hanja fan. I actually don't like them they're too difficult :-q Thanx god i'm not from Japan or China. and I don't really need this feature.

**Comment by jhyeon** [comment]
I use bspwm [http://github.com/baskerville/bspwm], a tiling window manager, and the uim master pops up the hanja candidate window to me, as shown in the attachment.  I sympathize with you having difficulty with hanjas but your personal complaint does not seem to be relevant to the resolution of this issue.
![candidate-window](https://cloud.githubusercontent.com/assets/6388362/15398958/b029be28-1e20-11e6-9358-d810b96503b6.png)

**Comment by wind0204** [comment]
Yes it is. I think I should contact sway developers. sway has a few annoying issues with chrome.. :-(

**Comment by parjanya** [comment]
I’m using the awesome WM, and I can see it, though sometimes it appears in the wrong monitor...

**Comment by wind0204** [comment]
sway fixed the overlay issue a few months ago.
