### ISSUE TITLE
uim-skk: q does not commit toggled kana string

### ISSUE THREAD

**Issue by fukuchidaisuke** [uim/uim#89]
In ▽ mode, one 'q' stroke following kana character adds 'q' at tail of the string.
At next 'q' stroke, toggled kana string is commited.
This is different from the third 'q' keybind described in [UimSKK](https://github.com/uim/uim-doc-ja/wiki/UimSkk#%E6%A8%99%E6%BA%96%E3%81%A7%E6%8C%87%E5%AE%9A%E3%81%95%E3%82%8C%E3%81%A6%E3%81%84%E3%82%8B%E3%82%AD%E3%83%BC%E8%A8%AD%E5%AE%9A)

I doubted 87bf935 and reverted the line 1589-1590 of skk.scm.
Then, the problem does not occur.
However, I don't know how affect other functions.

**Comment by dai-vdr** [comment]
related #39

**Comment by dai-vdr** [comment]
@fukuchidaisuke , confirmed.
Reverting 87bf935 line 1589-1590 not only resolves this problem but also resurrects problem at #39.

@tomykaira , Can you investigate both problems?

**Comment by dai-vdr** [comment]
#39 revert until resolve #89 and #39 problems.

**Comment by tomykaira** [comment]
Oops. Sorry for late response and inconvenience for all of you. I am not using uim now, so reverting is welcome.
