### ISSUE TITLE
Spurious ENABLE_DEBUG in qt5/immodule/quimplatforminputcontext.cpp

### ISSUE THREAD

**Issue by rcajal** [uim/uim#91]
There is a spurious #define ENABLE_DEBUG at the top of that file.

It causes tons of function calls to be logged to stdout even without --enable-debug passed to configure.

Some applications (QJackCtl, for example) log stdout for other uses. This debug output clogs their pipeline and causes malfunction (high CPU usage).

**Comment by dai-vdr** [comment]
closed by #125
